/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tcc.mma.ifpr.util.EditarFrame;

import static java.awt.Frame.NORMAL;
import java.security.MessageDigest;
import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import tcc.mma.ifpr.bean.Usuario;
import tcc.mma.ifpr.dao.UsuarioDAO;
import tcc.mma.ifpr.util.CadastrarFrame.CadastrarUsuario;
import tcc.mma.ifpr.util.ExcluirFrame.ExcluirUsuario;
import tcc.mma.ifpr.util.FabricaDeConexoes;
import tcc.mma.ifpr.util.TableModel.TableModelUsuario;
import tcc.mma.ifpr.util.Validar.Texto;

/**
 *
 * @author nnath
 */
public class EditarUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditarUsuario
     */
    public EditarUsuario() {
        initComponents();

    }

    int id = 0;
    int id1 = 0;

    public void pegarTabela() {

        try {
            Connection con = FabricaDeConexoes.criarConexaoParaMySQL();
            UsuarioDAO daoUsuario = new UsuarioDAO(con);
            List<Usuario> user = daoUsuario.retrieveAllFull();

            TableModelUsuario tableModelUsuario = new TableModelUsuario();
            jtUsuario.setModel(tableModelUsuario);

            for (int i = 0; i < user.size(); i++) {

                Usuario usuario = new Usuario();
                usuario.setId(user.get(i).getId());
                usuario.setNome(user.get(i).getNome());
                usuario.setLogin(user.get(i).getLogin());
                tableModelUsuario.addRow(usuario);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível atualizar a tabela Usuário!", "Atenção", NORMAL);
        }

    }

    public void arrumar() {

        txtID.setVisible(false);
        txtLogin.setVisible(false);
        txtNome.setVisible(false);
        jcMostrarSenha.setVisible(false);
        txtSenha.setVisible(false);
        txtConfirmarSenha.setVisible(false);
        jcbStatus.setVisible(false);
        jcbTipoUsuario.setVisible(false);
        lblConfirmarSenha.setVisible(false);
        lblD.setVisible(false);
        lblLogin.setVisible(false);
        lblNome.setVisible(false);
        lblSenha.setVisible(false);
        lblStatus.setVisible(false);
        lblTipoUser.setVisible(false);
        pegarTabela();

    }

    public void povoar() {
        try {
            Connection con = FabricaDeConexoes.criarConexaoParaMySQL();
            UsuarioDAO daoUsuario = new UsuarioDAO(con);
            Usuario usuario = daoUsuario.retrieve1(id1);

            txtID.setText(String.valueOf(usuario.getId()));
            txtLogin.setText(usuario.getLogin());
            txtNome.setText(usuario.getNome());
            jcbStatus.setSelectedIndex(usuario.getStatus() - 1);
            jcbTipoUsuario.setSelectedIndex(usuario.getTipoUsuario());
            txtSenha.setText(txtpass.getText());

        } catch (Exception e) {
        }
    }

    public String transformada(String pass) {

        String md = "";
        try {
            String senhaAdmin = pass;

            MessageDigest algorithm = MessageDigest.getInstance("SHA-256");
            byte messageDigestSenhaAdmin[] = algorithm.digest(senhaAdmin.getBytes("UTF-8"));

            StringBuilder hexStringSenhaAdmin = new StringBuilder();
            for (byte b : messageDigestSenhaAdmin) {
                hexStringSenhaAdmin.append(String.format("%02X", 0xFF & b));
            }
            String senhahexAdmin = hexStringSenhaAdmin.toString();

            md = String.valueOf(senhahexAdmin);

        } catch (Exception e) {
        }
        return md;

    }

    public int verificarSenha() {
        String um = txtSenha.getText();
        String dois = txtConfirmarSenha.getText();

        if (um.equals(dois)) {
            return 0;
        } else {
            return 1;
        }

    }

    public int verificarUser() {
        int confirmado = 2;
        try {
            Connection con = FabricaDeConexoes.criarConexaoParaMySQL();
            UsuarioDAO daoUsuario = new UsuarioDAO(con);
            int conf = daoUsuario.conferirUser(txtLogin.getText());

            if (conf == 1) {
                confirmado = 0;

            } else {
                confirmado = 1;

            }

        } catch (Exception e) {

        }

        return confirmado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtUsuario = new javax.swing.JTable();
        lblD = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblLogin = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        jcMostrarSenha = new javax.swing.JCheckBox();
        lblTipoUser = new javax.swing.JLabel();
        jcbTipoUsuario = new javax.swing.JComboBox<>();
        lblStatus = new javax.swing.JLabel();
        jcbStatus = new javax.swing.JComboBox<>();
        txtSenha = new javax.swing.JPasswordField();
        jbEditar = new javax.swing.JButton();
        jbCadastrarNovo = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        lblConfirmarSenha = new javax.swing.JLabel();
        txtConfirmarSenha = new javax.swing.JPasswordField();
        lblUser = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        jbConfirmar = new javax.swing.JButton();
        jcMostrarSenha1 = new javax.swing.JCheckBox();

        setClosable(true);
        setTitle("Editar Usuário");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jtUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Login"
            }
        ));
        jtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtUsuario);

        lblD.setText("ID:");

        txtID.setEditable(false);

        lblNome.setText("Nome:");

        lblLogin.setText("Login:");

        lblSenha.setText("Senha:");

        jcMostrarSenha.setText("Mostrar Senha");
        jcMostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcMostrarSenhaActionPerformed(evt);
            }
        });

        lblTipoUser.setText("Tipo de Usuário:");

        jcbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comum", "Administrador" }));
        jcbTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoUsuarioActionPerformed(evt);
            }
        });

        lblStatus.setText("Status:");

        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));

        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/mma/ifpr/img/editar.png"))); // NOI18N
        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbCadastrarNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/mma/ifpr/img/cadastrar.png"))); // NOI18N
        jbCadastrarNovo.setText("Cadastra Novo");
        jbCadastrarNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarNovoActionPerformed(evt);
            }
        });

        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/mma/ifpr/img/excluir.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/mma/ifpr/img/limpar.png"))); // NOI18N
        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        lblConfirmarSenha.setText("Confirmar Senha:");

        txtConfirmarSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConfirmarSenhaKeyPressed(evt);
            }
        });

        lblUser.setText("Login:");

        txtuser.setEditable(false);

        lblPass.setText("Senha:");

        jbConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/mma/ifpr/img/connect.png"))); // NOI18N
        jbConfirmar.setText("Confirmar");
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });

        jcMostrarSenha1.setText("Mostrar Senha");
        jcMostrarSenha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcMostrarSenha1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSenha)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcMostrarSenha)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblConfirmarSenha)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTipoUser)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblStatus)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblD)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblNome)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblLogin)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblUser)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblPass)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcMostrarSenha1)))
                                .addGap(0, 168, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(340, 340, 340)
                                .addComponent(jbConfirmar))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jbEditar)
                                .addGap(18, 18, 18)
                                .addComponent(jbCadastrarNovo)
                                .addGap(18, 18, 18)
                                .addComponent(jbExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(jbLimpar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbCadastrarNovo, jbEditar, jbExcluir, jbLimpar});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtConfirmarSenha, txtSenha});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPass)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcMostrarSenha1))
                .addGap(18, 18, 18)
                .addComponent(jbConfirmar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogin)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblD))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(jcMostrarSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConfirmarSenha)
                    .addComponent(txtConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoUser)
                    .addComponent(jcbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbEditar)
                    .addComponent(jbCadastrarNovo)
                    .addComponent(jbExcluir)
                    .addComponent(jbLimpar))
                .addContainerGap())
        );

        setBounds(0, 0, 963, 685);
    }// </editor-fold>//GEN-END:initComponents

    private void jcbTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTipoUsuarioActionPerformed

    private void jtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtUsuarioMouseClicked

        int linhaSelecionada = jtUsuario.getSelectedRow();

        if (linhaSelecionada != -1) {
            TableModelUsuario tbUsuario = (TableModelUsuario) jtUsuario.getModel();
            Usuario usuario = tbUsuario.getUsuario(jtUsuario.getSelectedRow());

            id = usuario.getId();

            arrumar();
            txtuser.setVisible(true);
            lblUser.setVisible(true);
            lblPass.setVisible(true);
            jbConfirmar.setVisible(true);
            txtpass.setVisible(true);
            jcMostrarSenha1.setVisible(true);
            txtuser.setText(null);
            txtpass.setText(null);
            jcMostrarSenha1.setSelected(false);

            try {

                Connection con = FabricaDeConexoes.criarConexaoParaMySQL();
                UsuarioDAO daoUsuario = new UsuarioDAO(con);
                Usuario usuario1 = daoUsuario.retrieve1(id);

                JOptionPane.showMessageDialog(null, "Por motivos de segurança, digite a senha correspondente ao usuário '" + usuario1.getNome() + "' para dar continuidade na edição!");
                txtuser.setText(usuario1.getLogin());
                id1 = id;
                id = 0;

            } catch (Exception e) {

            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jtUsuarioMouseClicked

    private void jcMostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcMostrarSenhaActionPerformed

        if (jcMostrarSenha.isSelected()) {
            txtSenha.setEchoChar((char) 0);
            txtConfirmarSenha.setEchoChar((char) 0);
        } else {
            txtSenha.setEchoChar('*');
            txtConfirmarSenha.setEchoChar('*');
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jcMostrarSenhaActionPerformed

    private void jcMostrarSenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcMostrarSenha1ActionPerformed

        if (jcMostrarSenha1.isSelected()) {
            txtpass.setEchoChar((char) 0);

        } else {
            txtpass.setEchoChar('*');

        }
// TODO add your handling code here:
    }//GEN-LAST:event_jcMostrarSenha1ActionPerformed

    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed

        int v = 1;

        if (txtuser.getText().isEmpty() && txtpass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os dados", "ERRO", NORMAL);
            txtuser.requestFocus();
            v = 0;
        } else {

            if (txtuser.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha o usuário", "ERRO", NORMAL);
                txtuser.requestFocus();
                v = 0;
            }
            if (txtpass.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha a senha", "ERRO", NORMAL);

                txtpass.requestFocus();
                v = 0;
            }
        }

        if (v == 1) {
            try {
                Connection con = FabricaDeConexoes.criarConexaoParaMySQL();
                UsuarioDAO daouser = new UsuarioDAO(con);
                Usuario user = daouser.retrieve(txtuser.getText());

                if (transformada(txtpass.getText()).equals(user.getPass())) {
                    txtuser.setVisible(false);
                    lblUser.setVisible(false);
                    lblPass.setVisible(false);
                    jbConfirmar.setVisible(false);
                    txtpass.setVisible(false);
                    jcMostrarSenha1.setVisible(false);

                    txtID.setVisible(true);
                    txtLogin.setVisible(true);

                    txtNome.setVisible(true);
                    jcMostrarSenha.setVisible(true);
                    txtSenha.setVisible(true);
                    txtConfirmarSenha.setVisible(true);
                    jcbStatus.setVisible(true);
                    jcbTipoUsuario.setVisible(true);
                    lblConfirmarSenha.setVisible(true);
                    lblD.setVisible(true);
                    lblLogin.setVisible(true);
                    lblNome.setVisible(true);

                    lblSenha.setVisible(true);
                    lblStatus.setVisible(true);
                    lblTipoUser.setVisible(true);

                    povoar();

                } else {
                    JOptionPane.showMessageDialog(null, "Senha Inválida!", "ERRO", NORMAL);
                    txtpass.setText("");
                    txtpass.requestFocus();
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Credenciais não encontradas!", "ERRO", NORMAL);
                txtuser.setText("");
                txtpass.setText("");
                txtuser.requestFocus();

            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jbConfirmarActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        Texto texto = new Texto();
        String retorno = texto.textoConverter(txtNome.getText());
        txtNome.setText(retorno);
        if (txtConfirmarSenha.getText().isEmpty() || txtLogin.getText().isEmpty()
                || txtNome.getText().isEmpty() || txtSenha.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Preencha todos os dados!", "Atenção", NORMAL);

        } else {

            int veri = verificarSenha();
            if (veri == 1) {

                JOptionPane.showMessageDialog(null, "As senhas não são correspondentes", "Atenção", NORMAL);
                txtSenha.setText("");
                txtConfirmarSenha.setText("");

            } else {

                int id = Integer.parseInt(txtID.getText());
                String nome = txtNome.getText();
                String login = txtLogin.getText();
                String pass = txtSenha.getText();
                String pass2 = transformada(pass);
                int tipoUsuario = jcbTipoUsuario.getSelectedIndex();
                int status = jcbStatus.getSelectedIndex() + 1;

                try {
                    Connection con = FabricaDeConexoes.criarConexaoParaMySQL();
                    UsuarioDAO daoUsuario = new UsuarioDAO(con);
                    Usuario usuario = new Usuario(id, nome, login, pass2, tipoUsuario, status);
                    daoUsuario.update(usuario);

                    JOptionPane.showMessageDialog(null, "Usuário '" + txtNome.getText() + "' atualizado com sucesso");

                    id = 0;
                    arrumar();

                    txtuser.setVisible(true);
                    lblUser.setVisible(true);
                    lblPass.setVisible(true);
                    jbConfirmar.setVisible(true);
                    txtpass.setVisible(true);
                    jcMostrarSenha1.setVisible(true);
                    txtuser.setText(null);
                    txtpass.setText(null);
                    jcMostrarSenha1.setSelected(false);
                } catch (Exception e) {

                }

            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed

        id = 0;
        arrumar();

        txtuser.setVisible(true);
        lblUser.setVisible(true);
        lblPass.setVisible(true);
        jbConfirmar.setVisible(true);
        txtpass.setVisible(true);
        jcMostrarSenha1.setVisible(true);
        txtuser.setText(null);
        txtpass.setText(null);
        jcMostrarSenha1.setSelected(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed

        ExcluirUsuario usuario = new ExcluirUsuario();
        getParent().add(usuario);
        usuario.setVisible(true);
        getParent().remove(1);
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbCadastrarNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarNovoActionPerformed

        CadastrarUsuario usuario = new CadastrarUsuario();
        getParent().add(usuario);
        usuario.setVisible(true);
        getParent().remove(1);

        // TODO add your handling code here:
    }//GEN-LAST:event_jbCadastrarNovoActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        pegarTabela();
        arrumar();        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void txtConfirmarSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmarSenhaKeyPressed

if (evt.getKeyCode() == evt.VK_ENTER) {
            jbConfirmar.doClick();

        }          // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmarSenhaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCadastrarNovo;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JCheckBox jcMostrarSenha;
    private javax.swing.JCheckBox jcMostrarSenha1;
    private javax.swing.JComboBox<String> jcbStatus;
    private javax.swing.JComboBox<String> jcbTipoUsuario;
    private javax.swing.JTable jtUsuario;
    private javax.swing.JLabel lblConfirmarSenha;
    private javax.swing.JLabel lblD;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTipoUser;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField txtConfirmarSenha;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
