/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tcc.mma.ifpr.util;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.URL;
import java.security.MessageDigest;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.TimeZone;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import tcc.mma.ifpr.bean.Usuario;
import tcc.mma.ifpr.dao.UsuarioDAO;

/**
 *
 * @author nnath
 */
public class LoginMma extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public LoginMma() {

        URL url = this.getClass().getResource("user.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbEsc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbcon = new javax.swing.JButton();
        lblhora = new javax.swing.JLabel();
        lblcon = new javax.swing.JLabel();
        lbldata = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        cbpass = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MMA Modas - login");
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jbEsc.setBackground(java.awt.Color.lightGray);
        jbEsc.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jbEsc.setForeground(new java.awt.Color(255, 51, 51));
        jbEsc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/mma/ifpr/img/exit.png"))); // NOI18N
        jbEsc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbEsc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbEscMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbEscMouseExited(evt);
            }
        });
        jbEsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEscActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 30)); // NOI18N
        jLabel1.setText("LOGIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(133, 133, 133)
                .addComponent(jbEsc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jbEsc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Usuário:");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("Senha:");

        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        txtuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtuserKeyPressed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/mma/ifpr/img/user.png"))); // NOI18N

        jbcon.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jbcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/mma/ifpr/img/connect.png"))); // NOI18N
        jbcon.setText("Conectar");
        jbcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbconActionPerformed(evt);
            }
        });
        jbcon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbconKeyPressed(evt);
            }
        });

        lblhora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/mma/ifpr/img/relogio.png"))); // NOI18N

        lblcon.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/mma/ifpr/img/bd.png"))); // NOI18N

        lbldata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/mma/ifpr/img/data.png"))); // NOI18N

        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpassKeyPressed(evt);
            }
        });

        cbpass.setText("Mostrar senha");
        cbpass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbpassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbldata, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblhora, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                .addComponent(lblcon, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(152, 152, 152))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(185, 185, 185))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(88, 88, 88)))
                                .addComponent(cbpass))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbcon)
                                .addGap(165, 165, 165))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(191, 191, 191))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbpass)
                .addGap(18, 18, 18)
                .addComponent(jbcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblhora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(lbldata, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbEscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEscActionPerformed

        try {
            Runtime.getRuntime().exec("tskill xampp-control");
            setVisible(false);
            Thread.sleep(3000);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, "Não foi possível fechar o xampp ", "Atenção", NORMAL);

        }

        System.exit(0);

    }//GEN-LAST:event_jbEscActionPerformed

    public String pass(String pass) {
        String md = "";
        try {
            String senhaAdmin = pass;

            MessageDigest algorithm = MessageDigest.getInstance("SHA-256");
            byte messageDigestSenhaAdmin[] = algorithm.digest(senhaAdmin.getBytes("UTF-8"));

            StringBuilder hexStringSenhaAdmin = new StringBuilder();
            for (byte b : messageDigestSenhaAdmin) {
                hexStringSenhaAdmin.append(String.format("%02X", 0xFF & b));
            }
            String senhahexAdmin = hexStringSenhaAdmin.toString();

            md = String.valueOf(senhahexAdmin);

        } catch (Exception e) {
        }
        return md;
    }

    private int bd() {
        int a = 0;
        try {

            Connection con = FabricaDeConexoes.criarConexaoParaMySQL();

            a = FabricaDeConexoes.conec();

        } catch (Exception e) {

            a = 0;
        }
        return a;
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        txtuser.requestFocus();

        int bd = bd();

        if (bd != 0) {
            lblcon.setText("Conectado com o banco!");

        } else {
            lblcon.setText("Sem conexão com o banco!");
            lblcon.setForeground(Color.red);
        }

        Date data = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        lbldata.setText(formato.format(data));

        Timer timer = new Timer(1000, new hora());
        timer.start();
    }//GEN-LAST:event_formWindowOpened
 Main main = new Main();
    private void jbconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbconActionPerformed
        int v = 1;
        int bd = bd();

        if (bd == 0) {
            JOptionPane.showMessageDialog(null, "Sem conexão com o banco!", "ERRO", NORMAL);
            txtuser.setText("");
            txtpass.setText("");
            txtuser.disable();
            txtpass.disable();
        } else {

            if (txtuser.getText().isEmpty() && txtpass.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha todos os dados", "ERRO", NORMAL);
                txtuser.requestFocus();
                v = 0;
            } else {

                if (txtuser.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Preencha o usuário", "ERRO", NORMAL);
                    txtuser.requestFocus();
                    v = 0;
                }
                if (txtpass.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Preencha a senha", "ERRO", NORMAL);

                    txtpass.requestFocus();
                    v = 0;
                }
            }

            if (v == 1) {
                try {
                    Connection con = FabricaDeConexoes.criarConexaoParaMySQL();
                    UsuarioDAO daouser = new UsuarioDAO(con);
                    Usuario user = daouser.retrieve(txtuser.getText().toLowerCase());

                    if (pass(txtpass.getText()).equals(user.getPass())) {
                       

                        setVisible(false);
                        String nome[] = user.getNome().split(" ");
                        String nomeFinal = "";
                        if (nome.length > 2) {
                            nomeFinal = nome[0].concat(" " + nome[nome.length - 1]);
                        } else {
                            nomeFinal = user.getNome();
                        }
                        main.lbluser.setText(nomeFinal);
                        main.lblcon.setText("Conectado");
                        main.tipoUsuario = user.getTipoUsuario();

                        telaLoading();

                    } else {
                        JOptionPane.showMessageDialog(null, "Senha Inválida!", "ERRO", NORMAL);
                        txtpass.setText("");
                        txtpass.requestFocus();
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Credenciais não encontradas!", "ERRO", NORMAL);
                    txtuser.setText("");
                    txtpass.setText("");
                    txtuser.requestFocus();

                }
            }
        }

    }//GEN-LAST:event_jbconActionPerformed

    private void telaLoading() {
        final Load load = new Load();
        load.setVisible(true);
        
        Thread t = new Thread() {
            @Override
            public void run() {
                main.controlarEstoque();
                for (int i = 0; i < 10; i++) {

                }
                load.dispose();

                main.setVisible(true);
            }
        };
        t.start();
    }

    private void jbconKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbconKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER) {
            jbcon.doClick();
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jbconKeyPressed

    private void txtuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuserKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtpass.requestFocus();

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserKeyPressed

    private void txtpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER) {
            jbcon.doClick();

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassKeyPressed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void cbpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbpassActionPerformed

        if (cbpass.isSelected()) {
            txtpass.setEchoChar((char) 0);
        } else {
            txtpass.setEchoChar('*');
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_cbpassActionPerformed

    private void jbEscMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbEscMouseEntered

        jbEsc.setBackground(Color.RED);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbEscMouseEntered

    private void jbEscMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbEscMouseExited

        jbEsc.setBackground(Color.lightGray);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbEscMouseExited

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginMma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginMma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginMma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginMma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        String line;
//        int instances = 0;
//        try {
//            Process processo = Runtime.getRuntime().exec("wmic.exe");
//            try ( BufferedReader br = new BufferedReader(new InputStreamReader(processo.getInputStream()))) {
//                OutputStreamWriter osw = new OutputStreamWriter(processo.getOutputStream());
//                osw.write("process where name='xampp-control.exe'");
//                osw.flush();
//                osw.close();
//                while ((line = br.readLine()) != null) {
//                    if (line.contains("xampp-control.exe")) {
//                        instances++;
//                    }
//                }
//
//            }
//        } catch (IOException ioe) {
//            ioe.printStackTrace();
//        }
//
//        if (instances == 0) {
//            try {
//                Process process = Runtime.getRuntime().exec("C:\\xampp/xampp-control.exe");
//
//            } catch (IOException e) {
//                JOptionPane.showMessageDialog(null, "Erro de inicialização do xampp", "Atenção!", NORMAL);
//
//            }
//
//            Thread.sleep(5000);
//        } else {
//            JOptionPane.showMessageDialog(null, "Xampp já inicializado!");
//        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginMma().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbEsc;
    private javax.swing.JButton jbcon;
    private javax.swing.JLabel lblcon;
    private javax.swing.JLabel lbldata;
    private javax.swing.JLabel lblhora;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables

    class hora implements ActionListener {

        public void actionPerformed(ActionEvent e) {

            DateFormat df = new SimpleDateFormat("HH:mm:ss ");
            df.setTimeZone(TimeZone.getTimeZone("GMT-03:00"));

            lblhora.setText(df.format(new Date()));

        }
    }
}
